apiVersion: v1
kind: Namespace
metadata:
  name: pvc-migrate-system
  labels:
    app.kubernetes.io/managed-by: pvc-migrate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-migrate
  namespace: pvc-migrate-system
