resources:
- bases/migrate.sealos.io_backuprepositories.yaml
- bases/migrate.sealos.io_backups.yaml
- bases/migrate.sealos.io_clusterbackups.yaml
- bases/migrate.sealos.io_copies.yaml
- bases/migrate.sealos.io_clustercopies.yaml
- bases/migrate.sealos.io_clustermigrations.yaml
- bases/migrate.sealos.io_clustermoves.yaml
- bases/migrate.sealos.io_clusterpodmigrations.yaml
- bases/migrate.sealos.io_clusterrenames.yaml
- bases/migrate.sealos.io_clusterreservations.yaml
- bases/migrate.sealos.io_clusterrestores.yaml
- bases/migrate.sealos.io_migrations.yaml
- bases/migrate.sealos.io_moves.yaml
- bases/migrate.sealos.io_podmigrations.yaml
- bases/migrate.sealos.io_renames.yaml
- bases/migrate.sealos.io_reservations.yaml
- bases/migrate.sealos.io_restores.yaml
